version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  twitter:
    container_name: twitter
    image: twitter:0.0.1
    ports:
      - "8080:8080"
